### ISSUE TITLE
Model not found error while running higlass

### ISSUE THREAD

**Issue by sachingadakh** [higlass/higlass-python#86]
import higlass
import higlass.tilesets
from higlass.client import Track, View
ts1 = higlass.tilesets.cooler('/mnt/data1/sachin/GAM/GAM_data/50kb/4DNFISUIYMOG.cool')
tr1 = Track('heatmap', tileset=ts1)
view1 = View([tr1])
display, server, viewconf = higlass.display([view1])
display

Error displaying widget: model not found

**Comment by manzt** [comment]
This is likely an issue with Jupyter widgets and not having the note book extension installed. The next release of HiGlass python will automatically enable extension when installed with `pip`.

**Comment by manzt** [comment]
Hi there. Are you able to try the pre release of higlass-python (`pip install --pre higlass-python`)? We have been working hard on this migration because of issues like this, and long term support of the older API is not planned.

**Comment by monnneee** [comment]
i @manzt ,I have solved it. The crux of this issue is the installing order of jupyter-widgets and ipywidgets. If install jupyter-widgets first, it does not work. If I install ipywidgets first, the jupyter-widgets package and @jupyter-widgets/jupyterlab-manager labextension will be installed automatically . So after I 'pip uninstall' jupyter-widgets and ipywidgets and re-install ipywidgets, **the error "Error displaying widget: model not found" was disappeared.**

In addition, I have another question. I found if I use 'jupyter labextension install higlass-jupyter' to install higlass-jupyter, I get error "The extension higlass-jupyter does not yet support the current version of JupyterLab' because of react version less than 17.0.1. So I used 'npm pack' download higlass-jupyter and changed package.json then installed it successfully:
$ jupyter labextension list
JupyterLab v3.6.2
/tools/miniconda3/share/jupyter/labextensions
jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
@jupyter-widgets/jupyterlab-manager v5.0.7 enabled OK (python, jupyterlab_widgets)
Other labextensions (built into JupyterLab)
app dir: /tools/miniconda3/share/jupyter/lab
higlass-jupyter v0.4.4 enabled OK

**But when run display, I got another error:**

[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'HiGlassDisplayModel' from module 'higlass-jupyter'
Error: No version of module higlass-jupyter is registered

Could you update ​higlass-jupyter's version with >=17.0.1 react? I guess there may be some hidden issues in higlass-jupyter that I installed.

**Comment by manzt** [comment]
Hi sorry, is there a particular reason that require the 0.4.8 version of higlass-python? We found the jupyter widget very challenging to maintain, and so the latest changes move away from requiring Jupyter widget installation. If you use the latest API, you should be able to avoid these issues all together.
